version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "7000:7000"
    environment:
      - MONGODB_URI=mongodb+srv://swarmx:swarmx@cluster0.tmcvyhu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
